add database, validations of input values
glorikum/Test-app pull request #1
Opened 2021-05-11 08:51 UTC by glorikum

2021-05-11 09:47 UTC, VladimirOnix requested changes

2021-05-11 09:47 UTC, VladimirOnix commented on app/src/main/java/com/onix/internship/survay/bindingadapter/BindingAdapters.kt
> +            editPasswordConfirmationLayout -> resources.getString(R.string.password_mismatch)
Pretty interest solution, but not very useful in case of code reusing. Create class or at least enum for error type and pass it into BindingAdapter instead of directly reference to id in layout

2021-05-11 09:47 UTC, VladimirOnix commented on app/src/main/java/com/onix/internship/survay/login/LoginViewModel.kt
> +class LoginViewModel(val database: UsersDao) : ViewModel(), Observable {
Why Observable needed here ?

2021-05-11 09:47 UTC, VladimirOnix commented on app/src/main/java/com/onix/internship/survay/login/LoginViewModel.kt
> +    private val uiScope = CoroutineScope(Dispatchers.Main + viewModelJob)
Is this created only for touching views or for DAO too ?

2021-05-11 09:47 UTC, VladimirOnix commented on app/src/main/java/com/onix/internship/survay/login/LoginViewModel.kt
> +                val usersNames = database.getUserLogin(userLogin.value!!)
Should be in background thread

2021-05-11 09:47 UTC, VladimirOnix commented on app/src/main/java/com/onix/internship/survay/register/RegisterViewModel.kt
> +                        firstName.value!!,
Why this fields required null safe invocation

2021-05-11 09:47 UTC, VladimirOnix commented on app/src/main/res/layout/admin_fragment.xml
> +
Is empty data needed ?

2021-05-13 10:25 UTC, glorikum commented on app/src/main/java/com/onix/internship/survay/bindingadapter/BindingAdapters.kt
> +            editPasswordConfirmationLayout -> resources.getString(R.string.password_mismatch)
I understood, saw in the example

2021-05-13 10:28 UTC, glorikum commented on app/src/main/java/com/onix/internship/survay/login/LoginViewModel.kt
> +class LoginViewModel(val database: UsersDao) : ViewModel(), Observable {
Using the example with the previous task, I thought it was necessary to track changes in the state of the fields.
In Slack, I saw comments that this is not necessary

2021-05-13 10:39 UTC, glorikum commented on app/src/main/res/layout/admin_fragment.xml
> +
Sorry, this is the next step. Stub

2021-05-13 11:11 UTC, TAEKsCode approved these changes

2021-05-17 11:55 UTC, VladimirOnix approved these changes

2021-05-17 11:55 UTC, merged